---
development:
  cloud_name: dceksz7xb
  api_key: '122591316153756'
  api_secret: HItQ2_kqXAm5jiL_w3PeTx23_H0
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dceksz7xb
  api_key: '122591316153756'
  api_secret: HItQ2_kqXAm5jiL_w3PeTx23_H0
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dceksz7xb
  api_key: '122591316153756'
  api_secret: HItQ2_kqXAm5jiL_w3PeTx23_H0
  enhance_image_tag: true
  static_file_support: false
